--
-- Copyright 2015-2016 USEF Foundation
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

--INSERT INTO SYNCHRONISATION_CONNECTION (ID, ENTITY_ADDRESS, IS_CUSTOMER, LAST_SYNCHRONISATION_TIME, LAST_MODIFICATION_TIME) VALUES (1, 'ean.871685900012636543', 'true', '2015-01-21 01:02:03', '2015-01-20 01:02:03');
--INSERT INTO SYNCHRONISATION_CONNECTION (ID, ENTITY_ADDRESS, IS_CUSTOMER, LAST_SYNCHRONISATION_TIME, LAST_MODIFICATION_TIME) VALUES (2, 'ean.121685900012636999', 'true', '2015-01-21 01:02:03', '2015-01-20 01:02:03');
INSERT INTO SYNCHRONISATION_CONNECTION (ID, ENTITY_ADDRESS, LAST_SYNCHRONISATION_TIME, LAST_MODIFICATION_TIME) VALUES (1, 'ean.871685900012636543', '2015-01-21 01:02:03', '2015-01-20 01:02:03');
INSERT INTO SYNCHRONISATION_CONNECTION (ID, ENTITY_ADDRESS, LAST_SYNCHRONISATION_TIME, LAST_MODIFICATION_TIME) VALUES (2, 'ean.121685900012636999', '2015-01-21 01:02:03', '2015-01-20 01:02:03');

INSERT INTO COMMON_REFERENCE_OPERATOR (ID,DOMAIN) VALUES(1,'usef-example.com');
INSERT INTO COMMON_REFERENCE_OPERATOR (ID,DOMAIN) VALUES(2,'usef-demo.com');
INSERT INTO COMMON_REFERENCE_OPERATOR (ID,DOMAIN) VALUES(3,'status-demo.com');

INSERT INTO SYNCHRONISATION_CONNECTION_STATUS (ID, SYNCHRONISATION_CONNECTION_ID, COMMON_REFERENCE_OPERATOR_ID, SYNCHRONISATION_CONNECTION_STATUS) VALUES (1, 1, 1, 'MODIFIED');
INSERT INTO SYNCHRONISATION_CONNECTION_STATUS (ID, SYNCHRONISATION_CONNECTION_ID, COMMON_REFERENCE_OPERATOR_ID, SYNCHRONISATION_CONNECTION_STATUS) VALUES (2, 1, 2, 'MODIFIED');
INSERT INTO SYNCHRONISATION_CONNECTION_STATUS (ID, SYNCHRONISATION_CONNECTION_ID, COMMON_REFERENCE_OPERATOR_ID, SYNCHRONISATION_CONNECTION_STATUS) VALUES (3, 2, 1, 'SYNCHRONIZED');
INSERT INTO SYNCHRONISATION_CONNECTION_STATUS (ID, SYNCHRONISATION_CONNECTION_ID, COMMON_REFERENCE_OPERATOR_ID, SYNCHRONISATION_CONNECTION_STATUS) VALUES (4, 2, 2, 'SYNCHRONIZED');
INSERT INTO SYNCHRONISATION_CONNECTION_STATUS (ID, SYNCHRONISATION_CONNECTION_ID, COMMON_REFERENCE_OPERATOR_ID, SYNCHRONISATION_CONNECTION_STATUS) VALUES (5, 1, 3, 'MODIFIED');
INSERT INTO SYNCHRONISATION_CONNECTION_STATUS (ID, SYNCHRONISATION_CONNECTION_ID, COMMON_REFERENCE_OPERATOR_ID, SYNCHRONISATION_CONNECTION_STATUS) VALUES (6, 2, 3, 'MODIFIED');

INSERT INTO METER_DATA_COMPANY (DOMAIN) VALUES ('mdc.usef-example.com');

INSERT INTO PTU_CONTAINER(ID, PHASE, PTU_DATE, PTU_INDEX) VALUES(1,'Settlement','2015-06-08',1);
INSERT INTO PTU_CONTAINER(ID, PHASE, PTU_DATE, PTU_INDEX) VALUES(2,'Settlement','2015-06-08',2);
INSERT INTO PTU_CONTAINER(ID, PHASE, PTU_DATE, PTU_INDEX) VALUES(3,'Settlement','2015-06-08',3);
INSERT INTO PTU_CONTAINER(ID, PHASE, PTU_DATE, PTU_INDEX) VALUES(4,'Settlement','2015-06-08',4);
INSERT INTO PTU_CONTAINER(ID, PHASE, PTU_DATE, PTU_INDEX) VALUES(5,'Settlement','2014-10-19',1);

INSERT INTO CONNECTION_GROUP(CONNECTION_GROUP_TYPE, USEF_IDENTIFIER, BRP_DOMAIN, AGR_DOMAIN, DSO_DOMAIN) VALUES ('AGR','agr.usef-example.com',null,'agr.usef-example.com',null);

INSERT INTO DOCUMENT(ID, SEQUENCE_NUMBER, CONNECTION_GROUP_ID, PTU_CONTAINER_ID) VALUES (1, 20150608110000456, 'agr.usef-example.com', 1);
INSERT INTO EXCHANGE(ID, PARTICIPANT_DOMAIN) VALUES (1, 'agr.usef-example.com');
INSERT INTO PTU_FLEXORDER(ID, FLEXOFFER_SEQUENCE, ACKNOWLEDGEMENT_STATUS) VALUES (1, 19700101000000001, 'ACCEPTED');

INSERT INTO DOCUMENT(ID, SEQUENCE_NUMBER, CONNECTION_GROUP_ID, PTU_CONTAINER_ID) VALUES (3, 20150630010000456, 'agr.usef-example.com', 5);
INSERT INTO EXCHANGE(ID, PARTICIPANT_DOMAIN) VALUES (3, 'agr.usef-example.com');
INSERT INTO PTU_FLEXORDER (ID, FLEXOFFER_SEQUENCE, ACKNOWLEDGEMENT_STATUS) VALUES (3, 20150630010000453, 'ACCEPTED');

INSERT INTO PLAN_BOARD_MESSAGE(ID, SEQUENCE_NUMBER, ORIGIN_SEQUENCE_NUMBER, PARTICIPANT_DOMAIN, DOCUMENT_STATUS, CONNECTION_GROUP_ID, DOCUMENT_TYPE, PTU_DATE) VALUES (1, 20150630010000456, 2222221, 'agr.usef-example.com', 'ACCEPTED', 'agr.usef-example.com', 'FLEX_ORDER', '2014-10-19');
