--
-- Copyright 2015-2016 USEF Foundation
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
INSERT INTO AGR.GRIDPOINT (ID, DSO_DOMAIN , ENTITY_ADDRESS, START_TIME, END_TIME) VALUES (-1, 'usef-example.com', 'ea1.1992-01.com.usef-example:gridpoint.11111111-1111-1111-1111', '2015-01-20 01:02:03', NULL);
